### ISSUE TITLE
Early hit windows

### ISSUE THREAD

**Issue by Beyley** [Thesola10/osu-DIVA#10]
Im not sure if this is intentional or not as ive never played the original games, but im unable to hit the entire beginning half of the hit windows (i cant hit early *at all*), and as someone who hits slightly early on rhythm games for timing it makes me miss uncontrollably when i very obviously should have hit it, which requires me to put a little mental timer in to delay my hits which heavily hinders my ability to play harder maps

Edit i think autoplay is also effected by this as it misses all notes

**Comment by Thesola10** [comment]
Can also reproduce, thanks!

**Comment by Thesola10** [comment]
Looking through [DivaHitWindows](https://github.com/Thesola10/osu-DIVA/blob/master/osu.Game.Rulesets.Diva/Scoring/DivaHitWindows.cs#L9) the way it declares `DifficultyRange` doesn't match what osu! stock gamemodes do (for example why is the 4th argument to Miss greater than the 3rd? osu! doesn't ever do that)
I'm gonna try to shuffle the vals around, but @Artemis-chan how did you get them?

**Comment by Thesola10** [comment]
For example, here's how osu!classic [does it](https://github.com/ppy/osu/blob/master/
osu.Game.Rulesets.Osu/Scoring/OsuHitWindows.cs#L10)

**Comment by Artemis-chan** [comment]
Honestly I don't remember but most likely i tweaked them manually, but the algo change could be possible as well as it used to work correctly at least for me.

**Comment by Thesola10** [comment]
Okay, waiting for your #13 review

**Comment by Thesola10** [comment]
Found the bug: In [DrawableDivaHitObject](https://github.com/Thesola10/osu-DIVA/blob/35ec1e2935718fa897f6c090b55c371d8148f7fc/osu.Game.Rulesets.Diva/Objects/Drawables/DrawableDivaHitObject.cs#L128), hits are ignored until the time of the hit (that is, the **center**, not the beginning, of the hit span)
