### ISSUE TITLE
Autoplay cannot input doubles

### ISSUE THREAD

**Issue by Thesola10** [Thesola10/osu-DIVA#35]
Double notes are a feature introduced in #5 which require hitting both keybindings for a given note, simulating DIVA F/F2nd double note behavior.

As it turns out, autoplay does not use a keyboard or controller, meaning it cannot make those inputs. As a result, autoplay fails all double notes, which isn't really the intended behavior.

A potential fix would be to patch the autoplay generator to add a "double" flag to its generated inputs.

**Comment by Artemis-chan** [comment]
fixed by https://github.com/Artemis-chan/osu-DIVA/commit/2fca9318d8b6898da5d7b1378e62cc3a4eab1b9a
