### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by Thesola10** [Thesola10/osu-DIVA#8]
This issue exists for documentation purposes and keeping track of Artemis-chan#8

**Comment by Artemis-chan** [comment]
I will be continuing development and updating the [Artemis-chan/osu-DIVA](https://github.com/Artemis-chan/osu-DIVA)

**Comment by Thesola10** [comment]
Which renders this repository obsolete. If I ever go forth with a rewrite of this concept, I will not be reusing the name or assets.
